#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
update_string="server_name _;\\n\\trewrite ^\\/redirect_me https:\\/\\/www.pinterest.com\\/pin\\/758997343472891932\\/ permanent;"
sudo sed -i "s/server_name _;/$update_string/" /etc/nginx/sites-enabled/default

# Test configurations for syntax errors
sudo nginx -t

# restart nginx after  changes
sudo service nginx restart
