#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
update_string="server_name _;\\n\\trewrite ^\\/redirect_me https:\\/\\/www.pinterest.com\\/pin\\/758997343472891932\\/ permanent;"
sudo sed -i "s/server_name _;/$update_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
update_string="listen 80 default_server;\\n\\terror_page 404 \\/404.html;\\n\\tlocation = \\/404.html {\\n\\t\\troot \\/var\\/www\\/html;\\n\\t\\tinternal;\\n\\t}"

sudo sed -i "s/listen 80 default_server;/$update_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
