#!/usr/bin/env bash
# Script that installs and configures HAProxy

# Install HAProxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy in the default configuration
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Create the HAProxy configuration directory if it doesn't exist
sudo mkdir -p /etc/haproxy

# Configure HAProxy
echo "
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 449959-web-01 54.237.12.204:80 check
    server 449959-web-02 3.86.13.209:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart
