#!/bin/env bash

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Set hostnames for web-01 and web-02
sudo hostnamectl set-hostname [449959]-web-01
sudo hostnamectl set-hostname [449959]-web-02

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [449959]-web-01:80 check
    server web-02 [449959]-web-02:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy
