#!/usr/bin/env bash
# Server-02 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school

# Username and IP Address
ssh -i ~/.ssh/school ubuntu@100.26.239.85
