#!/usr/bin/env bash
# Debugs Ubuntu container’s Nginx installation to listen on port 80
# Bash script with the minimum number of commands to automate your fix.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
