#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# With sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

MESSAGE ()
{
echo -e "I am invincible!!!"
}

trap "MESSAGE" SIGTERM

while true;
do
	echo -e "To infinity and beyond"
	sleep 2
done
