#!/usr/bin/env bash
#This script displays contents of file etc/passwd
#username, user id, Home directory path for user

while IFS=":" read -r line
do
	echo "$line" | cut -d":" -f1,4,7
done < /etc/passwd
