#!/usr/bin/env bash
# This script displays the time 12 hours and 59 minutes

hour=0
while [ "$hour" -lt 13 ];
do
	echo "Hour: $hour"
	minute=1
	while [ "$minute" -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done

	((hour++))
done
