#!/usr/bin/env bash
# This bash script gives information about the school file

file_name="school"

if [ -e "$file_name" ];
then
	echo "school file exists"

	if [ -s "$file_name" ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file_name" ];
	then
		echo "school is a regular file"
	else
		echo "(nothing)"
	fi
else
	echo "school file does not exist"
fi
