#!/usr/bin/env bash
# This bash script displays all active IPv4 IPs on the machine it’s executed on.
ips=$(ip -o -4 addr show scope global | awk '{print $4}' | cut -d'/' -f1)

for ip in $ips; do
  echo $ip
done
